# -*- coding: utf-8 -*-
"""Fault detection system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EjUtIDYVbiRs4YF_wm5n4Ghrrfx4xXr7
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score, classification_report,
    confusion_matrix, roc_auc_score
)
import joblib
import warnings
warnings.filterwarnings('ignore')

# 1. Load Dataset


df = pd.read_csv("fault_detection_dataset_large.csv")

print("=" * 55)
print("  SOLAR FROST AI — Fault Detection Training")
print("=" * 55)
print(f"Total samples  : {len(df)}")
print(f"Normal  (0)    : {(df['fault'] == 0).sum()}")
print(f"Fault   (1)    : {(df['fault'] == 1).sum()}")
print()

X = df[["Temperature", "Humidity", "Battery_Level"]]
y = df["fault"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 2. Train


model = RandomForestClassifier(
    n_estimators=200,
    max_depth=20,
    min_samples_leaf=3,
    class_weight="balanced",
    n_jobs=-1,
    random_state=42
)
model.fit(X_train, y_train)

# 3. Evaluate

pred      = model.predict(X_test)
pred_prob = model.predict_proba(X_test)[:, 1]
acc       = accuracy_score(y_test, pred)
roc_auc   = roc_auc_score(y_test, pred_prob)
cv        = cross_val_score(model, X, y, cv=5, scoring='accuracy')

print(f"Test Accuracy     : {acc * 100:.2f}%")
print(f"ROC-AUC           : {roc_auc:.4f}")
print(f"Cross-Val (5-fold): {cv.mean()*100:.2f}% ± {cv.std()*100:.2f}%")
print()
print(classification_report(y_test, pred, target_names=["Normal", "Fault"]))

cm = confusion_matrix(y_test, pred)
print("Confusion Matrix:")
print(f"  True  Normal : {cm[0][0]}")
print(f"  False Alarm  : {cm[0][1]}")
print(f"  Missed Fault : {cm[1][0]}  ← most critical to minimize")
print(f"  True  Fault  : {cm[1][1]}")
print()

print("Feature Importance:")
for feat, imp in zip(X.columns, model.feature_importances_):
    bar = "█" * int(imp * 50)
    print(f"  {feat:<18} {bar}  {imp * 100:.1f}%")
print()

# 4. Live Inference Tests


print("Live Inference Tests:")
print("-" * 75)

test_cases = [
    ([5,  50, 95], "NORMAL", "Ideal cold storage"),
    ([15, 60, 75], "NORMAL", "Warm day, cooling fine"),
    ([8,  55,  8], "NORMAL", "Night — low bat, temp still cold"),
    ([6,  50, 12], "NORMAL", "Pre-dawn battery drain"),
    ([10, 65, 18], "NORMAL", "Solar recovery in progress"),
    ([18, 70,  5], "NORMAL", "Very low bat, but temp cold = ok"),
    ([36, 55, 70], "FAULT",  "Overtemperature"),
    ([48, 60, 50], "FAULT",  "Severe overtemp"),
    ([18, 92, 65], "FAULT",  "High humidity — seal broken"),
    ([25, 50,  8], "FAULT",  "Low bat + warm temp = compressor off"),
    ([30, 50,  5], "FAULT",  "Compressor failed, battery dead"),
    ([42, 88,  6], "FAULT",  "Combined critical"),
    ([33, 76, 15], "FAULT",  "Gradual drift"),
]

all_correct = True
for inp, expected, label in test_cases:
    p    = model.predict([inp])[0]
    prob = model.predict_proba([inp])[0]
    pred_str = "HEALTHY " if p == 0 else "FAULT "
    conf     = max(prob) * 100
    correct  = (expected == "NORMAL" and p == 0) or (expected == "FAULT" and p == 1)
    mark     = "✓" if correct else "✗ WRONG"
    if not correct:
        all_correct = False
    print(f"  {label:<42} T={inp[0]:>4}°C H={inp[1]:>3}% B={inp[2]:>3}%  →  {pred_str} ({conf:.0f}%) {mark}")

print()
if all_correct:
    print("  ALL CASES CORRECT — model is ready for demo")
else:
    print("  Some cases still wrong — check dataset balance")
print()

# ===============================
# 5. Save
# ===============================

joblib.dump(model, "fault_detection_model_balanced.pkl")
import os
print(f"Saved: fault_detection_model_balanced.pkl  ({os.path.getsize('fault_detection_model_balanced.pkl')//1024} KB)")

try:
    from google.colab import files
    files.download("fault_detection_model_balanced.pkl")
except:
    print("(Not in Colab — file saved locally)")