# -*- coding: utf-8 -*-
"""Solar_LSTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p-tOGPzwgWZz46wtJ4dMrGi-5CVkMbPX
"""

pip install pandas numpy scikit-learn tensorflow matplotlib

from google.colab import drive
drive.mount('/content/drive')

# ===============================
# Solar Forecast LSTM Model
# ===============================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Input
from tensorflow.keras.models import load_model

# ===============================
# 1 Load Dataset
# ===============================

power = pd.read_csv("/Plant_1_Generation_Data.csv")
weather = pd.read_csv("/Plant_1_Weather_Sensor_Data.csv")

# Convert 'DATE_TIME' columns to datetime objects for consistent merging
power['DATE_TIME'] = pd.to_datetime(power['DATE_TIME'], format='%d-%m-%Y %H:%M')
weather['DATE_TIME'] = pd.to_datetime(weather['DATE_TIME'], format='%Y-%m-%d %H:%M:%S')

# Merge datasets
data = pd.merge(power, weather, on="DATE_TIME")

# Select important features
data = data[
    [
        "AC_POWER",
        "IRRADIATION",
        "AMBIENT_TEMPERATURE",
        "MODULE_TEMPERATURE"
    ]
]

# Remove missing values
data = data.dropna()

# ===============================
# 2 Normalize Data
# ===============================

scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(data)

# ===============================
# 3 Create Time Sequences
# ===============================

def create_sequences(data, seq_length=24):

    X = []
    y = []

    for i in range(len(data) - seq_length):

        X.append(data[i:i+seq_length])
        y.append(data[i+seq_length][0])

    return np.array(X), np.array(y)

X, y = create_sequences(scaled_data)

# ===============================
# 4 Train Test Split
# ===============================

split = int(len(X) * 0.8)

X_train = X[:split]
X_test = X[split:]

y_train = y[:split]
y_test = y[split:]

# ===============================
# 5 Build LSTM Model
# ===============================

model = Sequential([

    Input(shape=(X.shape[1], X.shape[2])),

    LSTM(64, return_sequences=True),

    LSTM(32),

    Dense(1)

])

model.compile(
    optimizer="adam",
    loss="mse"
)

model.summary()

# ===============================
# 6 Train Model
# ===============================

history = model.fit(

    X_train,
    y_train,

    epochs=20,
    batch_size=32,

    validation_data=(X_test, y_test)

)

# ===============================
# 7 Save Model
# ===============================

model.save("solar_forecast_lstm.keras")

print("Model saved successfully")

# ===============================
# 8 Prediction
# ===============================

pred = model.predict(X_test)

# ===============================
# 9 Plot Results
# ===============================

plt.figure(figsize=(10,5))

plt.plot(y_test[:200], label="Actual")
plt.plot(pred[:200], label="Predicted")

plt.title("Solar Power Forecasting")
plt.legend()

plt.show()

# ===============================
# 10 Download Model (Google Colab)
# ===============================

try:
    from google.colab import files
    files.download("solar_forecast_lstm.keras")
except:
    print("Download step skipped (not running in Colab)")

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
from sklearn.preprocessing import LabelEncoder
import joblib

# load dataset
data = pd.read_csv("/content/commodity_price.csv")

# rename columns
data = data.rename(columns={
    "Min_x0020_Price": "Min_Price",
    "Max_x0020_Price": "Max_Price",
    "Modal_x0020_Price": "Modal_Price"
})

# select columns
data = data[
    [
        "State",
        "District",
        "Market",
        "Commodity",
        "Min_Price",
        "Max_Price",
        "Modal_Price"
    ]
]

# remove missing values
data = data.dropna()

# encode categorical data
le = LabelEncoder()

data["State"] = le.fit_transform(data["State"])
data["District"] = le.fit_transform(data["District"])
data["Market"] = le.fit_transform(data["Market"])
data["Commodity"] = le.fit_transform(data["Commodity"])

# features and target
X = data.drop("Modal_Price", axis=1)
y = data["Modal_Price"]

# split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# train model
model = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

model.fit(X_train, y_train)

# predictions
pred = model.predict(X_test)

# accuracy
score = r2_score(y_test, pred)

print("Model accuracy:", score)

# save model
joblib.dump(model, "market_price_model.pkl")

print("Model saved successfully")

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
import joblib


data = pd.read_csv("/content/Agriculture_price_dataset (1).csv")


data.columns = data.columns.str.strip()

data = data.rename(columns={
    "STATE":"State",
    "District Name":"District",
    "Market Name":"Market"
})


data["Price Date"] = pd.to_datetime(data["Price Date"])

data["Month"] = data["Price Date"].dt.month
data["Day"] = data["Price Date"].dt.day


data = data[
    [
        "State",
        "District",
        "Market",
        "Commodity",
        "Min_Price",
        "Month",
        "Day",
        "Modal_Price"
    ]
]

data = data.dropna()


encoder = LabelEncoder()

data["State"] = encoder.fit_transform(data["State"])
data["District"] = encoder.fit_transform(data["District"])
data["Market"] = encoder.fit_transform(data["Market"])
data["Commodity"] = encoder.fit_transform(data["Commodity"])


X = data.drop("Modal_Price", axis=1)
y = data["Modal_Price"]


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ===============================
# 8 Train Random Forest
# ===============================

model = RandomForestRegressor(
    n_estimators=20,
    max_depth=16,
    n_jobs=-1,
    random_state=42
)

model.fit(X_train, y_train)

# ===============================
# 9 Evaluate
# ===============================

pred = model.predict(X_test)

accuracy = r2_score(y_test, pred)

print("Model Accuracy:", accuracy)

# ===============================
# 10 Save model
# ===============================

joblib.dump(model,"market_price_model.pkl")

print("Model saved successfully")

import os

size = os.path.getsize("/content/market_price_model.pkl") / (1024*1024)
print("Model size:", size, "MB")

# =================================
# Solar Forecast LSTM Training
# =================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import joblib

from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, Input

# =================================
# 1 Load Dataset
# =================================

power = pd.read_csv("/content/Plant_1_Generation_Data.csv") # Corrected file path
weather = pd.read_csv("/content/Plant_1_Weather_Sensor_Data.csv")

power['DATE_TIME'] = pd.to_datetime(power['DATE_TIME'], format='%d-%m-%Y %H:%M')
weather['DATE_TIME'] = pd.to_datetime(weather['DATE_TIME'], format='%Y-%m-%d %H:%M:%S') # Specified format for consistency

data = pd.merge(power, weather, on="DATE_TIME")

data = data[[
    "AC_POWER",
    "IRRADIATION",
    "AMBIENT_TEMPERATURE",
    "MODULE_TEMPERATURE"
]]

data = data.dropna()

# =================================
# 2 Separate Features and Target
# =================================

X = data[[
    "IRRADIATION",
    "AMBIENT_TEMPERATURE",
    "MODULE_TEMPERATURE"
]]

y = data["AC_POWER"]

# =================================
# 3 Normalize
# =================================

scaler_X = MinMaxScaler()
scaler_y = MinMaxScaler()

X_scaled = scaler_X.fit_transform(X)
y_scaled = scaler_y.fit_transform(y.values.reshape(-1,1))

# Save scalers
joblib.dump(scaler_X,"scaler_X.pkl")
joblib.dump(scaler_y,"scaler_y.pkl")

# =================================
# 4 Create Sequences
# =================================

SEQ_LENGTH = 24

X_seq = []
y_seq = []

for i in range(len(X_scaled) - SEQ_LENGTH):

    X_seq.append(X_scaled[i:i+SEQ_LENGTH])
    y_seq.append(y_scaled[i+SEQ_LENGTH])

X_seq = np.array(X_seq)
y_seq = np.array(y_seq)

print("Shape:",X_seq.shape)

# =================================
# 5 Train Test Split
# =================================

split = int(len(X_seq)*0.8)

X_train = X_seq[:split]
X_test = X_seq[split:]

y_train = y_seq[:split]
y_test = y_seq[split:]

# =================================
# 6 Build LSTM Model
# =================================

model = Sequential([

    Input(shape=(SEQ_LENGTH,3)),

    LSTM(64,return_sequences=True),
    Dropout(0.2),

    LSTM(32),

    Dense(16),
    Dense(1)

])

model.compile(
    optimizer="adam",
    loss="mse"
)

model.summary()

# =================================
# 7 Train
# =================================

history = model.fit(

    X_train,
    y_train,

    epochs=25,
    batch_size=32,

    validation_data=(X_test,y_test)
)

# =================================
# 8 Save Model
# =================================

model.save("solar_lstm_model2.keras")

print("Model Saved")

# =================================
# 9 Predict
# =================================

pred = model.predict(X_test)

# Convert back to original scale
pred_real = scaler_y.inverse_transform(pred)
y_test_real = scaler_y.inverse_transform(y_test)

# =================================
# 10 Plot
# =================================

plt.figure(figsize=(12,5))

plt.plot(y_test_real[:200],label="Actual")
plt.plot(pred_real[:200],label="Predicted")

plt.legend()
plt.title("Solar Power Prediction")

plt.show()