# -*- coding: utf-8 -*-
"""Spoilage and cooling rl model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cpq6WXltRVRKYwINoVtTBWykCmryCU7h
"""

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import joblib

# load dataset
data = pd.read_csv("/content/spoilage_dataset.csv")

X = data[["temperature","hours"]]
y = data["spoilage_risk"]

X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2,random_state=42
)

model = RandomForestClassifier(n_estimators=200)

model.fit(X_train,y_train)

pred = model.predict(X_test)

acc = accuracy_score(y_test,pred)

print("Spoilage Model Accuracy:",acc)

joblib.dump(model,"spoilage_model.pkl")

print("Model saved")

pip install stable-baselines3

import gym
import numpy as np
from gym import spaces

class CoolingEnv(gym.Env):

    def __init__(self):

        self.observation_space = spaces.Box(
            low=np.array([0,0]),
            high=np.array([50,1000]),
            dtype=np.float32
        )

        self.action_space = spaces.Discrete(2)

        self.temperature = 6
        self.solar_power = 500

    def step(self,action):

        if action == 1:
            self.temperature -= 0.5
            energy = 2
        else:
            self.temperature += 0.3
            energy = 0

        penalty = max(0,self.temperature-8)

        reward = -(energy + penalty)

        state = np.array([self.temperature,self.solar_power])

        done = False

        return state,reward,done,{}

    def reset(self):

        self.temperature = 6
        self.solar_power = 500

        return np.array([self.temperature,self.solar_power])

from stable_baselines3 import PPO

# Install shimmy for compatibility with Gym environments
!pip install shimmy>=2.0

env = CoolingEnv()

model = PPO("MlpPolicy",env,verbose=1)

model.learn(total_timesteps=10000)

model.save("cooling_rl_model")

print("RL model trained")

from stable_baselines3 import PPO

model = PPO.load("cooling_rl_model")

state = env.reset()

action, _ = model.predict(state)

print("Cooling action:", action)